Check for modified files in build
Modifies the Checks workflow to build everything and check for modified
files. This way we'll know if a change to the code resulted in an
uncommitted change to one of the manifests.

diff --git a/.github/workflows/checks.yaml b/.github/workflows/checks.yaml
--- a/.github/workflows/checks.yaml
+++ b/.github/workflows/checks.yaml
@@ -24,7 +24,15 @@ jobs:
           cache-dependency-path: '**/go.sum'
 
       - name: Test
-        run: make test
+        run: |
+          touch api/v1alpha1/* # forces manifest regeneration, some changes (e.g. controller-gen update) don't reflect in code
+          make test
 
       - name: Check for uncommitted changes
-        run: git diff --exit-code -- docs/reference
+        run: |
+          if ! git diff --exit-code -s; then
+            for f in $(git diff --exit-code --name-only); do
+              echo "::error file=$f,line=1,col=1,endColumn=1::File was modified in build"
+            done
+            exit 1
+          fi
